services:
  model-downloader:
    image: alpine
    container_name: llama-cpp-downloader
    volumes:
      - ./models:/models
      - ./download_model.sh:/download_model.sh
    env_file: .env
    command: sh /download_model.sh

  llama-cpp:
    image: llama-cpp-turboquant:server-cuda
    container_name: llama-cpp-qwen
    restart: unless-stopped

    depends_on:
      model-downloader:
        condition: service_completed_successfully

    ports:
      - "${LLAMA_PORT}:8080"

    volumes:
      - ./models:/models
      - ./start.sh:/start.sh

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    env_file: .env

    entrypoint: ["/bin/sh", "/start.sh"]
