services:
  model-downloader:
    image: alpine
    container_name: llama-cpp-downloader
    volumes:
      - ./models:/models
      - ./download_model.sh:/download_model.sh
    env_file: .env
    command: sh /download_model.sh

  llama-cpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-cpp-qwen
    restart: unless-stopped

    depends_on:
      model-downloader:
        condition: service_completed_successfully

    ports:
      - "${LLAMA_PORT}:8080"

    volumes:
      - ./models:/models

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    command:
      [
        "-m", "/models/${MODEL_DIR}/${MODEL_FILENAME}",

        "--host", "0.0.0.0",
        "--port", "8080",
        "--webui",
        "--jinja",

        "--reasoning", "${REASONING}",

        "-ngl", "${N_GPU_LAYERS}",
        "-c", "${CTX_SIZE}",

        "--cache-type-k", "${CACHE_TYPE_K}",
        "--cache-type-v", "${CACHE_TYPE_V}",

        "--temp", "${TEMPERATURE}",
        "--top-p", "${TOP_P}",
        "--top-k", "${TOP_K}",
        "--min-p", "${MIN_P}",
        "--presence-penalty", "${PRESENCE_PENALTY}",
        "--repeat-penalty", "${REPEAT_PENALTY}",
        "-n", "${MAX_TOKENS}"
      ]
